version: '3.8'
services:
  app:
    container_name: rni_web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/rni_db
    depends_on:
      - db
    networks:
      - rni_network

  db:
    image: postgres:15-alpine
    container_name: rni_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-rni_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rni_network

volumes:
  postgres_data:


networks:
  rni_network:
    driver: bridge
